#!/bin/bash
## Place this file in following location '/etc/update-motd.d/'
## and set permissions to 755.
## Last modified: Jan 4, 2017
## Created by: alejandro gallego (alegalle@cisco.com)
# echo ""
mgmt=$(ifquery --list | egrep -v lo | sort | head -1)
imgmt=$(ifconfig $mgmt |egrep -o '([0-9]+\.){3}[0-9]+' |head -1)
cat <<EOF

+****************  Welcome to VIRL Server!  ****************+
|    To manage VIRL please use UWM web interface.           |
|    Point your browser to the URL shown below using        |
|    the following default credentials:                     |
|                                                           |
|    User Name: uwmadmin                                    |
|    Password: password                                     |
|                                                           |
|    UWM URL:                                               |
|    http://$imgmt:19400
|                                                           |
+****************  Welcome to VIRL Server!  ****************+

EOF

ifquery --list | egrep -v lo | sort | while read intf
do
ipadr=$(ifconfig $intf |egrep -o '([0-9]+\.){3}[0-9]+' |head -1)
    sudo ethtool $intf | grep 'Link detected: yes' > /dev/null
        if [ $? -ne 0 ] ; then
        printf ">>>>%sInterface $intf DOWN%s\n"
        else
        printf "%s    $intf: $ipadr\n"
        fi
done
