#!/bin/bash
## Place this file in following location '/etc/update-motd.d/'
## and set permissions to 755.
## Last modified: Jan 13, 2017
## Created by: alejandro gallego (alegalle@cisco.com)
# echo ""
######

mgmt=$(awk '$2 == 00000000 { print $1 }' /proc/net/route)
maddr=$(ip addr show dev $mgmt | awk '$1 == "inet" { sub("/..", "", $2); print $2}')
cat <<EOF

+*******************  Cisco VIRL Server  *******************+
|    To manage VIRL please use UWM web interface.           |
|    Point your browser to the URL shown below using        |
|    the following default credentials:                     |
|                                                           |
|    User Name: uwmadmin                                    |
|    Password: password                                     |
|                                                           |
|    UWM URL:                                               |
|    http://$maddr
|                                                           |
+*******************  Cisco VIRL Server  *******************+
EOF
printf "\nVIRL Server Interfaces: \n"
ifquery --list | egrep -v lo | sort | while read intf
do
ipadr=$(ip addr show dev $intf |awk '$1 == "inet" { sub("/..", "", $2); print $2}')
    sudo ethtool $intf | grep 'Link detected: yes' > /dev/null
        if [ $? -ne 0 ] ; then
        printf ">>>>%sInterface $intf DOWN%s\n"
        else
        printf "%s    $intf: $ipadr\n"
        fi
done
echo ""